# Generated by Django 3.2.8 on 2021-11-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('fund_Ownership', models.IntegerField()),
                ('initial_investment_date', models.IntegerField()),
                ('initial_investment', models.IntegerField()),
                ('total_invested', models.IntegerField()),
                ('reported_value_end_of_Q2', models.IntegerField()),
                ('unrealised_gain', models.IntegerField()),
                ('MOIC', models.IntegerField()),
                ('year', models.DateField()),
            ],
        ),
    ]
