# Generated by Django 3.2.8 on 2021-11-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='fund_Ownership',
            new_name='fund_ownership',
        ),
        migrations.AddField(
            model_name='investment',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
