# Generated by Django 3.2.8 on 2021-11-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_investment_fund_ownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='MOIC',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
