# Generated by Django 3.2.8 on 2021-11-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_investment_moic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
