# Generated by Django 3.2.8 on 2021-11-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_investment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='initial_investment_date',
            field=models.DateField(),
        ),
    ]
