# Generated by Django 3.2.8 on 2021-11-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_investment_initial_investment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='initial_investment_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='year',
            field=models.DateField(null=True),
        ),
    ]
