# Generated by Django 3.2.8 on 2021-11-02 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211102_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='initial_investment_date',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='year',
        ),
    ]
