# Generated by Django 3.2.8 on 2021-11-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211102_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='year',
            field=models.DateField(null=True),
        ),
    ]
