# Generated by Django 3.2.8 on 2021-11-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_investment_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='initial_investment_date',
            field=models.DateField(null=True),
        ),
    ]
