# Generated by Django 3.2.8 on 2021-12-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_investment_fair_market_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='fair_market_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
