# Generated by Django 3.2.8 on 2021-12-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_investment_fair_market_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='company',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
