# Generated by Django 3.2.8 on 2021-12-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bluehaven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('total_commited', models.IntegerField()),
                ('net_investment', models.IntegerField()),
                ('total_bhi_shares_remaining', models.IntegerField()),
                ('latest_share_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fair_market_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_coc_returns', models.DecimalField(decimal_places=2, max_digits=5)),
                ('year', models.IntegerField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
